apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: camp2025
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        image: raketanamarse/camp2025:echoserver
        ports:
        - containerPort: 8000
        env:
        - name: AUTHOR
          value: "YourName"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
      imagePullSecrets:
      - name: regcred
