apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: camp2025
spec:
  selector:
    app: echoserver
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
